name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./assets
    
